stages:
  preprocess:
    cmd: python musicnet/preprocess.py
    deps:
    - data/MusicNet/musicnet/musicnet
    params:
    - shared
    - preprocess
    outs:
    - data/train:
        cache: false
    - data/val:
        cache: false
  train:
    cmd: python musicnet/train.py
    deps:
    - data/train
    - data/val
    params:
    - shared
    - train
    outs:
    - musicnet/model.keras:
        persist: true
    - musicnet/model.weights.h5:
        persist: true
    - dvclive/metrics.json:
        persist: true
    - dvclive/plots:
        persist: true
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
