stages:
  convert_midi:
    cmd: python musicnet/preprocessing/midi_to_wav/convert.py
    deps:
    - data/MusicNet/musicnet/musicnet
    params:
    - params.yaml
    outs:
    - data/preprocessed/midi_to_wav:
        cache: false
        persist: true
  preprocess:
    cmd: python musicnet/preprocessing/wav_specs_and_notes/preprocess.py
    deps:
    - data/MusicNet/musicnet/musicnet
    params:
    - params.yaml
    outs:
    - data/preprocessed/wav_specs_and_notes:
        cache: false
        persist: true
  train:
    cmd: python musicnet/models/cnn/train.py
    deps:
    - data/preprocessed/wav_specs_and_notes
    params:
    - params.yaml
    outs:
    - musicnet/models/cnn/model.keras
    - dvclive/metrics.json
    - dvclive/plots
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
