midi_to_wav:
  programs_whitelist: [0]
wav_specs_and_notes:
  use_converted_midis: true
  preprocessor:
    chunk_size_sec: 10
    chunk_shift_sec: 5
    target_sr: 44100
    note_rounding: 0.01
    # Can be set to False
    spectogram:
      n_fft: 2205 # 50 ms
      hop_length: 441 # 10 ms
      min_hz: 0
      n_filters: 200
      unit: decibels
  datasets:
    train:
      size: 0.8
      file_count: 30
    val:
      size: 0.2
      file_count: 10
transformer:
  architecture: encoder-only
  dataset_size: 1.0
  d_model: 128
  num_layers: 4
  num_heads: 8
  dff: 512
  mha_dropout: 0.0
  input_dropout: 0.0
  batch_size: 8
  epochs: 200
  warmup_steps: 10000
  max_lr: 0.0002
cnn:
  dataset_size: 1.0
  n_layers: 5
  n_neurons: 2048
  activation: gelu
  kernel_size: 16
  batch_size: 8
  epochs: 80
  lr: 0.001
  dropout_rate: 0.0
  conv_type: separable
wavenet:
  batch_size: 8
  dataset_size: 1.0
  activation: relu
  epochs: 10
  lr: 0.0002
  layers:
    - wavenet_kernel: 256
      n_maps: 20
      pooling: False
    - wavenet_kernel: 256
      n_maps: 40
      pooling: 10
    - wavenet_kernel: 64
      n_maps: 80
      pooling: False
    - wavenet_kernel: 64
      n_maps: 160
      pooling: 8
    - wavenet_kernel: 16
      n_maps: 320
      pooling: False
    - wavenet_kernel: 16
      n_maps: 640
      pooling: 4