defaults:
  - config
  - dataset/val/wav_source: synth_midi_to_wav
  - dataset/test/wav_source: music_net_midi_to_wav
  - override dataset/default/wav_source: synth_midi_to_wav
  - _self_

dataset:
  default:
    wav_source:
      min_note: 20
      max_note: 105
      notes_std: 20
      track_length_per_note: 900
      max_silmultaneous_notes: 9
  val:
    wav_source:
      min_note: 20
      max_note: 105
      notes_std: 20
      track_length_per_note: 300
      max_silmultaneous_notes: 9
  test:
    split: [0.0, 0.2]
    wav_source:
      programs_whitelist: [0]
model:
  n_neurons: 1000
  kernel_size: 3
  n_layers: 5
  epochs: 25
  lr: 0.0025
  activation: GELU