defaults:
  - config
  - dataset/val/wav_source: synth_midi_to_wav
  - dataset/test/wav_source: synth_midi_to_wav
  - override dataset/default/wav_source: synth_midi_to_wav
  - _self_

dataset:
  default:
    wav_source:
      min_note: 20
      max_note: 25
      notes_std: 10
      track_length_per_note: 900
  val:
    wav_source:
      min_note: 20
      max_note: 25
      notes_std: 10
      track_length_per_note: 300
  test:
    wav_source:
      min_note: 20
      max_note: 30
      notes_std: 10
      track_length_per_note: 300
model:
  n_neurons: 200
  kernel_size: 3
  n_layers: 5
  epochs: 5
  lr: 0.01
  activation: GELU