stages:
  convert_midi:
    cmd: python ../../preprocessing/midi_to_wav/convert.py
    deps:
    - ../../../data/MusicNet/musicnet/musicnet
    params:
    - ../../../params.yaml:
      - midi_to_wav
    outs:
    - ../../../data/preprocessed/midi_to_wav:
        cache: false
        persist: true
  preprocess:
    cmd: python ../../preprocessing/wav_specs_and_notes/preprocess.py
    deps:
    - ../../../data/MusicNet/musicnet/musicnet
    params:
    - ../../../params.yaml:
      - wav_specs_and_notes
      - midi_to_wav.programs_whitelist
    outs:
    - ../../../data/preprocessed/wav_specs_and_notes:
        cache: false
        persist: true
  train:
    cmd: python train.py
    deps:
    - ../../../data/preprocessed/wav_specs_and_notes
    params:
    - ../../../params.yaml:
      - midi_to_wav.programs_whitelist
      - wav_specs_and_notes.preprocessor.n_filters
      - wav_specs_and_notes.use_converted_midis
      - transformer
    outs:
    - model.keras
    - dvclive/metrics.json
    - dvclive/plots
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
